### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by Zerocreative0815** [Cryxnoob/TeamProjectTH-BingenEP-1#26]
Release Version 1.0

**Comment by nipafx** [comment]
Here's how to do a release (pardon my German):

* `master` auschecken
* mit `mvn clean install` und `java-jar target/...jar` sicherstellen, dass alles funktioniert
* in der `pom.xml` bei der Version `-SNAPSHOT` entfernen
* nochmal `mvn clean install` und die JAR aus dem `target`-Ordner (beachte, dass `-SNAPSHOT` fehlt) irgendwohin kopieren
* neuen Commit auf `master` mit der Message "Release version 1.0" (oder so)
* den Commit taggen
* in der `pom.xml` die Version `2.0-SNAPSHOT` eintragen
* neuen Commit auf `master` mit der Message "Start work on 2.0" (oder so)
* alles pushen (mit tags)
* auf GitHub das Releases-Menü finden, _Edit_ klicken, aus dem Tag ein Release machen und die JAR anhängen

Note that there is no pull request involved - this is one of the few things that happens directly on `master`.

**Comment by nipafx** [comment]
Just to clarify: No release before [milestone 1](https://github.com/Cryxnoob/TeamProjectTH-BingenEP-1/milestone/1) is done.

PS: I'm signing off for tonight. Should be back online some time tomorrow.

**Comment by nipafx** [comment]
:tada:
