### ISSUE TITLE
Maven/Kotlin project

### ISSUE THREAD

**Issue by Zerocreative0815** [Cryxnoob/TeamProjectTH-BingenEP-1#3]
- create a Maven/Kotlin project that contains a simple HelloWorld.kt class with a main method printing "Hello, World." and that successfully builds a JAR

**Comment by nipafx** [comment]
The current `.gitignore` does not exclude the `target` folder Maven will create. Make sure to exclude it when working on this issue.

The Travis integration should be its own issue.

**Comment by Zerocreative0815** [comment]
but i can't write it as simple like this (picture)
<img width="428" alt="bildschirmfoto 2017-08-03 um 20 01 40" src="https://user-images.githubusercontent.com/28270142/28935920-53d1d9a0-7886-11e7-99cc-0315c45d3e4b.png">
