### ISSUE TITLE
Add license to README

### ISSUE THREAD

**Issue by Zerocreative0815** [Cryxnoob/TeamProjectTH-BingenEP-1#5]
- add a license and document it in the README
decide on a language (e.g. by discussing it on the issue that belongs to this task) and document it in the README:

**Comment by Zerocreative0815** [comment]
what license we have to use??

**Comment by nipafx** [comment]
Whichever you want. I'd recommend an open source license, though. Some links:

* [Open source for absolute beginners](http://oss-watch.ac.uk/resources/beginners)
* [Open-Source Licensing For Dummies](http://www.binpress.com/blog/2013/06/21/open-source-licensing-for-dummies/).
* [An Introduction to Open-source Licenses](https://www.sitepoint.com/introduction-to-open-source-licenses/)

**Comment by nipafx** [comment]
The license file is called `license.txt`. Please rename it to `LICENSE.txt`, so that GitHub recognizes it and shows the license information.
