### ISSUE TITLE
Launch explanation

### ISSUE THREAD

**Issue by Zerocreative0815** [Cryxnoob/TeamProjectTH-BingenEP-1#7]
- extend the README to tell users how to launch the application

**Comment by Zerocreative0815** [comment]
how can i tell the users how to launch the application when there is no real application yet ?....or is it more like an introduction to it? @nicolaiparlog

**Comment by nipafx** [comment]
Yes, it makes sense to do #3 first. :wink:

**Comment by Zerocreative0815** [comment]
But it is only a code that says  hello world....thats not a real application ?

**Comment by nipafx** [comment]
What do you mean it's no real application? You spent some hours creating it and when executed it prints something on the command line. Sure that's an application!

I admit, it's a useless one :wink:, but you'll address that in the second block.
